# Generated by Django 5.1.6 on 2025-02-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_users',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='system_users',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
