# Generated by Django 5.1.6 on 2025-02-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_system_users_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_users',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='system_users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
