# Generated by Django 5.1.6 on 2025-02-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_system_users_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='name_ext',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
