# Generated by Django 5.1.6 on 2025-02-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_professor_name_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_users',
            name='userrole',
            field=models.CharField(choices=[('Student', 'Student'), ('Professor', 'Professor'), ('Administrator', 'Administrator')], default='Student', max_length=20),
        ),
    ]
