# Generated by Django 5.1.6 on 2025-02-28 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_alter_sectionstudents_section'),
        ('homepage', '0006_alter_professor_user_alter_userinformation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.course'),
        ),
    ]
