# Generated by Django 5.1.6 on 2025-02-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_userinformation_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='semester',
            field=models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('3rd Semester', '3rd Semester'), ('4th Semester', '4th Semester'), ('5th Semester', '5th Semester')], max_length=100, null=True),
        ),
    ]
