# Generated by Django 5.1.6 on 2025-03-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_userinformation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_users',
            name='id_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
