# Generated by Django 5.1.6 on 2025-03-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_system_users_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='academic_status',
        ),
    ]
