# Generated by Django 5.1.6 on 2025-03-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_remove_userinformation_academic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_users',
            name='avatar',
            field=models.ImageField(default='avatar.png', null=True, upload_to='profile-avatar/'),
        ),
    ]
