# Generated by Django 5.1.6 on 2025-03-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_alter_system_users_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_users',
            name='new_user',
            field=models.BooleanField(default=True),
        ),
    ]
