# Generated by Django 5.1.6 on 2025-03-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_system_users_new_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='guardian_contact',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='guardian_relationship',
        ),
    ]
