# Generated by Django 5.1.6 on 2025-03-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_remove_userinformation_guardian_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='year_level',
            field=models.IntegerField(null=True),
        ),
    ]
