# Generated by Django 5.1.6 on 2025-03-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_alter_userinformation_year_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_users',
            name='firstName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='system_users',
            name='lastName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
