# Generated by Django 5.1.6 on 2025-03-04 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_system_users_firstname_system_users_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
