# Generated by Django 5.1.6 on 2025-03-04 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_alter_professor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='academic_rank',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='office_hours',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='office_location',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='research_interests',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='specialization',
        ),
    ]
