# Generated by Django 5.1.6 on 2025-03-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_remove_professor_academic_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='name_ext',
            field=models.CharField(default='Prof.', max_length=50),
        ),
    ]
