# Generated by Django 5.1.6 on 2025-03-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_alter_professor_name_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='hire_date',
            field=models.DateField(null=True),
        ),
    ]
