# Generated by Django 5.1.6 on 2025-03-04 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_alter_professor_hire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='employee_id',
        ),
    ]
