# Generated by Django 5.1.6 on 2025-02-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionstudents',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
