# Generated by Django 5.1.6 on 2025-02-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_coursesection_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='room',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
