# Generated by Django 5.1.6 on 2025-02-25 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_coursesection_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='course',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.CreateModel(
            name='SubjectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('3rd Semester', '3rd Semester'), ('4th Semester', '4th Semester'), ('5th Semester', '5th Semester')], max_length=100, null=True)),
                ('course_code', models.CharField(max_length=50, null=True)),
                ('course_title', models.CharField(max_length=100, null=True)),
                ('units', models.IntegerField(null=True)),
                ('laboratory', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.course')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('day', models.CharField(max_length=100, null=True)),
                ('time_from', models.TimeField(null=True)),
                ('time_to', models.TimeField(null=True)),
                ('room', models.CharField(max_length=100, null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.subjectlist')),
            ],
        ),
        migrations.AlterField(
            model_name='professorschedule',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.subjectsection'),
        ),
        migrations.AlterField(
            model_name='sectionstudents',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.subjectsection'),
        ),
        migrations.DeleteModel(
            name='CourseSection',
        ),
    ]
