# Generated by Django 5.1.6 on 2025-02-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_rename_course_name_course_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectlist',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
