# Generated by Django 5.1.6 on 2025-02-28 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_alter_subjectsection_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionstudents',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_section', to='administrator.subjectsection'),
        ),
    ]
