# Generated by Django 5.1.6 on 2025-02-28 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_enrollmentconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentconfirmation',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
