# Generated by Django 5.1.6 on 2025-02-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_enrollmentconfirmation_date_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentconfirmation',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enrollmentconfirmation',
            name='status',
            field=models.CharField(choices=[('Approve', 'Approve'), ('Disapprove', 'Disapprove'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
    ]
