# Generated by Django 5.1.6 on 2025-02-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_enrollmentconfirmation_confirm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentconfirmation',
            name='confirm',
        ),
    ]
