# Generated by Django 5.1.6 on 2025-03-01 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_remove_enrollmentconfirmation_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionstudents',
            name='confirmed',
        ),
    ]
