# Generated by Django 5.1.6 on 2025-03-01 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_remove_sectionstudents_confirmed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation', models.BooleanField(default=False)),
                ('Subject', models.BooleanField(default=False)),
                ('section', models.BooleanField(default=False)),
                ('section_confirmation', models.BooleanField(default=False)),
                ('print_regform', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
