# Generated by Django 5.1.6 on 2025-03-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_enrollmentprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentprogress',
            name='accounting',
            field=models.BooleanField(default=False),
        ),
    ]
