# Generated by Django 5.1.6 on 2025-03-01 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_enrollmentprogress_accounting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollmentprogress',
            old_name='Subject',
            new_name='subject',
        ),
    ]
