# Generated by Django 5.1.6 on 2025-03-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_rename_subject_enrollmentprogress_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentconfirmation',
            name='schedule_confirmation',
            field=models.BooleanField(default=True),
        ),
    ]
