# Generated by Django 5.1.6 on 2025-03-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_enrollmentconfirmation_schedule_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentconfirmation',
            name='schedule_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
