# Generated by Django 5.1.6 on 2025-03-01 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0019_alter_enrollmentconfirmation_schedule_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionstudents',
            name='date_tagged',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
