# Generated by Django 5.1.6 on 2025-03-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0022_alter_professorschedule_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentconfirmation',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
