# Generated by Django 5.1.6 on 2025-03-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0024_alter_enrollmentconfirmation_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentconfirmation',
            name='date_updated',
            field=models.DateTimeField(),
        ),
    ]
