# Generated by Django 5.1.6 on 2025-03-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0027_event_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentconfirmation',
            name='date_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
